### ISSUE TITLE
action calculation from PK2PK broken

### ISSUE THREAD

**Issue by mihofer** [pylhc/omc3#155]
when getting action from PK2PK, larger errorbar compared to amplitude method
traced back to {} in kick.py

**Comment by rogeliotomas** [comment]
hi,is this why RDT calculation is wrong?ciaorogelio
-------- Message d'origine --------De : mihofer <notifications@github.com> Date : 29.01.20  7:22 PM  (GMT+01:00) À : pylhc/omc3 <omc3@noreply.github.com> Cc : Subscribed <subscribed@noreply.github.com> Objet : [pylhc/omc3] action calculation from PK2PK broken (#155) when getting action from PK2PK, larger errorbar compared to amplitude method
traced back to {} in kick.py

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pylhc/omc3/issues/155?email_source=notifications\u0026email_token=AAUNH6GPJQTMNRZKTJFJDHTRAHCOJA5CNFSM4KNJKDZKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IJTWF2A",
"url": "https://github.com/pylhc/omc3/issues/155?email_source=notifications\u0026email_token=AAUNH6GPJQTMNRZKTJFJDHTRAHCOJA5CNFSM4KNJKDZKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IJTWF2A",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by mihofer** [comment]
Fixed in #158
